#! /usr/bin/env bash
echo "Starting To Create A Quick Wordpress Site and the plugin $1"

if ! command -v wp &> /dev/null
then
    echo "wp cli could not be found"
    exit 1
fi

## CHECKING FLAGS
# Initialize a variable to indicate if the flag is set
# Loop through all the arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --plugin=*)
      plugin="${1#*=}"
      ;;
		--blueprint)
			blueprint="${1#*=}"
			;;
    *)
			#
      ;;
  esac
  shift # Move to the next argument
done


mkdir -p public
cd public

wp core download

cd ..
mkdir -p bin

FILE_URL="https://raw.githubusercontent.com/joshmkennedy/wpnow/main/bin/start-site"
OUTPUT_FILE="bin/start-site"
curl -L "$FILE_URL" -o "$OUTPUT_FILE"
# Check if the download was successful
if [ $? -eq 0 ]; then
  echo "File downloaded successfully as $OUTPUT_FILE"
	chmod +x "$OUTPUT_FILE"
else
  echo "Failed to download file"
fi


if [ -z $plugin ]; then
	echo "Not Creating a plugin"
else
	echo "Creating the plugin $name"
	cd public/wp-content/plugins
	npx @wordpress/create-block $plugin --template @wordpress/create-block-interactive-template
	cd ../../../
fi

# Download and use the specified blueprint
blueprint_url=""
if [ -z $blueprint ]; then
	#allows for a local blueprint to be used
	echo "Using the default blueprint"
	blueprint_url="https://raw.githubusercontent.com/joshmkennedy/wpnow/main/bp.json"
else
	if [[ "$blueprint" != "bp.json" ]]; then
		blueprint_url=$blueprint	
	fi
fi

if [ -z $blueprint_url ]; then
	echo "Using local bp.json"
else
	echo "Downloading Blueprint ..."
	curl -L "$blueprint_url" -o bp.json
	#TODO: may want to add a flag to see if user wants this
	curl -L "https://raw.githubusercontent.com/joshmkennedy/wpnow/main/post-content" -o post-content
fi

echo -e "Finished!\n Run the following command to start the site"
echo "./bin/start-site";
echo -e "Then cd into public/wp-content/plugins/$plugin\n and run \`npm start\` to get a dev server going"   
